// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjOW2f1jAH5bNHPZ4WGGk6L45aVzotseY',
    appId: '1:723139239097:web:7a0c060acf0f0620360f68',
    messagingSenderId: '723139239097',
    projectId: 'gymhabit-aa72f',
    authDomain: 'gymhabit-aa72f.firebaseapp.com',
    storageBucket: 'gymhabit-aa72f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyIOduRXJqfFrXLVu_mDHl3uIlaAALQsw',
    appId: '1:723139239097:android:947a00462f354878360f68',
    messagingSenderId: '723139239097',
    projectId: 'gymhabit-aa72f',
    storageBucket: 'gymhabit-aa72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEY4VIKp-aYdLaMnc6sAm2dpSreoXQnDk',
    appId: '1:723139239097:ios:f3e46856955421d8360f68',
    messagingSenderId: '723139239097',
    projectId: 'gymhabit-aa72f',
    storageBucket: 'gymhabit-aa72f.appspot.com',
    androidClientId: '723139239097-5tvhis5jl21u9ae63nl42grp89fise8i.apps.googleusercontent.com',
    iosClientId: '723139239097-tjbemc68gkk088uvc83lt9fjjdk60mqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEY4VIKp-aYdLaMnc6sAm2dpSreoXQnDk',
    appId: '1:723139239097:ios:f3e46856955421d8360f68',
    messagingSenderId: '723139239097',
    projectId: 'gymhabit-aa72f',
    storageBucket: 'gymhabit-aa72f.appspot.com',
    androidClientId: '723139239097-5tvhis5jl21u9ae63nl42grp89fise8i.apps.googleusercontent.com',
    iosClientId: '723139239097-tjbemc68gkk088uvc83lt9fjjdk60mqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchFlutter',
  );
}
